name: bundle executable
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.0.1
      with:
        bun-version: latest
    - name: Install
      run: bun install
    - name: Build Executable
      run: bun build ./index.ts --compile --outfile ssrs-cli
    - name: Make File Executable
      run: chmod +x ssrs-cli
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        # Artifact name
        name: ssrs-cli
        # A file, directory or wildcard pattern that describes what to upload
        path: ssrs-cli 
        retention-days: 90        
